name: vtandroid
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0  # Added
  intl: ^0.19.0              # Downgraded from ^0.20.2 to satisfy local_auth constraints
  path_provider: ^2.0.0      # Added
  cupertino_icons: ^1.0.8
  http: ^0.13.0             # Added
  local_auth: ^2.1.3        # Added for biometrics

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Added

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/verithesia_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/verithesia_icon.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
